### ISSUE TITLE
Pls fix!😃

### ISSUE THREAD

**Issue by BinoWassabi** [hiking93/PokeX#2]
The apk cant install parsing 

Lollipop 64

**Comment by hiking93** [comment]
Which device are you running at?

**Comment by kureijir** [comment]
I had the same problem, Lollipop on Xperia Z1. Installing the downloaded APK gave me "There was a problem parsing the package" error, while Xposed Installer said it was invalid or incompatible and refuse to install.

**Comment by jumznatic** [comment]
fix plssss.. apk cant install it said there was a problem parsing the package, not working on kitkat and lollipop

**Comment by hiking93** [comment]
Should be fixed in version 1.5, but not yet tested because I can't reach any rooted Lollipop or KitKat device by now. Download the latest apk from repo or build from source to test it out.
http://repo.xposed.info/module/com.sparkslab.pokex
