### ISSUE TITLE
Floating window doesn't appear over app

### ISSUE THREAD

**Issue by engise** [hiking93/PokeX#3]
When I installed the module for the first time it worked perfectly and I was able to play 20~ minutes, but when I closed the PoGo app and the module and tried an hour later the overlay doesn't appear over the app and PoGo is telling me "GPS signal not found"

Tried reinstalling the module and restarting the device, but no luck...

**Comment by hiking93** [comment]
I've done some improvements in version 1.4, please download and try the new version.
http://repo.xposed.info/module/com.sparkslab.pokex

If you encountered the same problem, please feel free to reopen the issue.
