### ISSUE TITLE
Support needed

### ISSUE THREAD

**Issue by banboy247** [hiking93/PokeX#5]
Hey hiking,
I recently downloaded your app but it wasn't really working the way I wanted it. Now I like to delete the app and go back to Pokemon go controls but every time I say to spawn at Manhattan, I spawn in China...

Tip for your app: implement Google maps so people don't Niet coordinates to their spawn

**Comment by hiking93** [comment]
Which version of the app are you using? Some known bugs exist in old versions.

**Comment by banboy247** [comment]
I just learned how to properly uninstall an exposed module. There is no problem anymore... I'm just stupid xD

**Comment by hiking93** [comment]
Glad you found a solution!
